version: '3.5'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backendnet
  
  db_test:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=BackendTest_test
    ports:
      - 5433:5432
    networks:
      - backendnet
  
  app:
    build:
      context: .
    depends_on:
      - db_test
      - db
    ports:
      - 3000:3000
    networks:
      - backendnet

networks:
  backendnet: